version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "9000:9000"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: hotelbooking
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
